[qtmozembed] Fix loading for pages loaded with pushState. Fixes JB#56556
sailfishos/qtmozembed pull request #36
Opened 2022-01-04 14:43 UTC by mkenttala

2022-01-04 16:34 UTC, rainemak requested changes
I'd rather fix following lines from browser side:

https://github.com/sailfishos/sailfish-browser/blob/next/apps/core/declarativewebcontainer.cpp#L1041

https://github.com/sailfishos/sailfish-browser/blob/next/apps/core/declarativewebcontainer.cpp#L199

I vaguely remember that as some point of time there was a reason to wait for domContentLoaded and I think it was due to tab creation. As we now create new tabs when requested, without resolving url beforehand, changing above two lines to listen/call firstPaint should be enough and would not change domContentLoaded behaviour.

2022-01-04 16:34 UTC, rainemak commented on src/qmozview_p.cpp
>      mViewIface->firstPaint(aX, aY);
This introduces possibility that domContent is not loaded before we got a painted frame (no sure how would I do that but). I'd rather follow ```painted``` property on the browser side.

2022-01-05 06:33 UTC, rainemak commented on src/qmozview_p.cpp
>      mViewIface->firstPaint(aX, aY);
This was it https://github.com/sailfishos/sailfish-browser/pull/485 ( https://github.com/sailfishos/sailfish-browser/commit/0af8ad3563e8b70577de4bb2828f10537f7136ab ).

The issue was other way around that first paint is not always triggered and domContentLoaded is there as a final fallback. 

So adding connection to the firstPaint and extending guards (similarly also within side of the updateActiveTabRendered) should do the same.

```
connect(m_webPage.data(), &QOpenGLWebPage::firstPaint,
              this, &DeclarativeWebContainer::updateActiveTabRendered, Qt::UniqueConnection);
...
if (m_webPage->completed() && m_webPage->active() && (m_webPage->isPainted() || m_webPage->domContentLoaded())) {
    m_webPage->update();
}
```

2022-01-05 07:34 UTC, rainemak commented on src/qmozview_p.cpp
>      mViewIface->firstPaint(aX, aY);
+
```
-    readyToPaint: resourceController.videoActive ? webView.visible && !resourceController.displayOff : webView.visible && webView.contentItem && webView.contentItem.domContentLoaded
+    readyToPaint: resourceController.videoActive ? webView.visible && !resourceController.displayOff : webView.visible && webView.contentItem
+                                                   && (webView.contentItem.domContentLoaded || webView.contentItem.painted)
```

2022-01-05 09:11 UTC, mkenttala commented
Moving fix to sailfish-browser.

2022-01-05 09:11 UTC, closed without merging